# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network requests to Segment, Inc. to উন্নতি collecting
# stats on Pods used in order to improve CocoaPods tooling.
# For more information, see https://cocoapods.org/legal
# We recommend that you keep this enabled, but feel free to disable it if noted desired.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "Generated.xcconfig not found. To fix, run \"flutter build ios\" or \"flutter run\" and try again."
  end

  File.read(generated_xcode_build_settings_path).each_line do |line|
    if line.match(/FLUTTER_ROOT=/)
      return line.split('=').last.strip
    end
  end
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
